spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: k6051601
        url: jdbc:mysql://localhost:3306/bt
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
        show-sql: true
    redis:
        host: localhost
        port: 6379
        password: 1234
    session:
        storage-type: redis
        timeout: 3600



server:
    servlet:
        session:
            cookie:
                name: JSESSIONID

