spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 1234
    url: jdbc:mysql://127.0.0.1:3307/bt
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  redis:
    host: localhost
    port: 6380
    password: 1234
  session:
    storage-type: redis
    timeout: 3600



server:
  servlet:
    session:
      cookie:
        name: JSESSIONID

